User.create :name => 'admin', :email => 'admin@admin.com', :password => 'password', :password_confirmation => 'password', :admin => 'true'
Team.create(name: 'River Plate')
Team.create(name: 'Boca Juniors')
Team.create(name: 'Racing Club')
Team.create(name: 'Independiente')
Team.create(name: 'San Lorenzo')
Team.create(name: 'Rosario Central')
Team.create(name: 'Newells Old Boys')
Team.create(name: 'Belgrano')
Team.create(name: 'Estudiantes de La Plata')
Team.create(name: 'Banfield')
Team.create(name: 'Tigre')
Team.create(name: 'Lanus')
Team.create(name: 'Gimnasia de La Plata')
Team.create(name: 'San Martin de San Juan')
Team.create(name: 'Quilmes')
Team.create(name: 'Union de Santa Fe')
Team.create(name: 'Temperley')
Team.create(name: 'Argentinos Juniors')
Team.create(name: 'Aldosivi')
Team.create(name: 'Velez Sarfield')
Team.create(name: 'Defensa y Justicia')
Team.create(name: 'Sarmiento')
Team.create(name: 'Olimpo')
Team.create(name: 'Colon de Santa Fe')
Team.create(name: 'Godoy Cruz')
Team.create(name: 'Huracan')
Team.create(name: 'Atletico Rafaela')
Team.create(name: 'Arsenal')
Team.create(name: 'Nueva Chicago')
Team.create(name: 'Crucero del Norte')